### ISSUE TITLE
Document Process for Sharing Users Between Environments

### ISSUE THREAD

**Issue by xiujiao** [genesis-community/jumpbox-genesis-kit#1]
Run `genesis new uswest2-main` and configure users and then run `genesis new uswest2-standby`, it will not bring over users which are already in `uswest2-main` to `uswest2-standby`.
If we put users setting in `uswest2.yml`, then when we run `genesis new uswest2-*.yml`, it will detect users already in `uswest2.yml`.

How do we modify the kit so that we do not need to repeatedly configure the same users on different jumpbox deployments?

**Comment by jhunt** [comment]
Perhaps just create the `uswest2-standby` file without using `genesis new`?

**Comment by jhunt** [comment]
I believe this needs to be handled in documentation.
