### ISSUE TITLE
Add updated shield CLI to jumpbox

### ISSUE THREAD

**Issue by cwb124** [genesis-community/jumpbox-genesis-kit#16]
Using shield CLI is easier with more modern shield CLI versions like v8.x.  I am not sure what version is in Jumpbox as there is no documented version argument but newer one would be cool.

**Comment by jhunt** [comment]
8.0.17 of SHIELD should have the ability to just download the right binary from the SHIELD core itself.  At that point, we're better off removing `shield` from the Jumpbox altogether.

**Comment by daviddob** [comment]
Resolved in https://github.com/genesis-community/jumpbox-genesis-kit/releases/tag/v1.0.3
