### ISSUE TITLE
`generate-vpn-config` should not create missing certs

### ISSUE THREAD

**Issue by dennisjbell** [genesis-community/jumpbox-genesis-kit#21]
Since the generate vpn config step can be run multiple time as things change (or when multiple jumpbox deployments share the same vault for ease of use), it has been experienced that errors on the call create new certs that litter the vault rather than catch the error.

**Comment by jhunt** [comment]
How about adding a `-f` flag to the addon, to be used like this:

```
$ echo "this should fail..."
$ bosh do my-jumpbox -- generate-vpn-config missing@example.com

$ echo "this should not!"
$ bosh do my-jumpbox -- generate-vpn-config -f missing@example.com
```
