### ISSUE TITLE
kit is requiring cert for openvpn feature that isn't turned on

### ISSUE THREAD

**Issue by 7hunderbird** [genesis-community/jumpbox-genesis-kit#25]
We've searched through our environment.yml files in our generated jumpbox-deployments.  None are using `openvpn` feature.

So today when we removed the `openvpn/certs/server` cert it wouldn't pass the check command.

```
$ genesis check c-ops.yml 

Using vault at https://10.174.0.132:443.
Verifying availability...ok

Checking availability of the 'c-ops' BOSH director...Downloading cloud config from 'c-ops' BOSH director...

[c-ops] running cloud-config and environmental parameters checks...
  [Checking cloud config]
  ✔  vm_type 'jumpbox' exists
  ✔  disk_type 'jumpbox' exists
  ✔  network 'jumpbox' exists
  cloud-config [OK]

[c-ops] running credentials and certificates checks...
[openvpn/certs/server] is missing

[c-ops] PREFLIGHT FAILED
```

**Comment by 7hunderbird** [comment]
The last piece of context is that doomsday was letting us know our `openvpn` certs in the jumpbox release were coming due.  So that's why we deleted the cert and then tested the check.

**Comment by norman-abramovitz** [comment]
Fixed on the master branch and the fix will be in the next release.
